# Generated by Django 3.0.5 on 2020-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, upload_to='store/product/')),
                ('avaliable', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='product_category', to='store.Category')),
            ],
        ),
    ]
