# Generated by Django 3.0.5 on 2020-04-27 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20200419_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qanda',
            options={'verbose_name': ' Q and A', 'verbose_name_plural': 'Qs and As'},
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='name',
        ),
        migrations.AddField(
            model_name='qanda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_QandA', to=settings.AUTH_USER_MODEL),
        ),
    ]
