# Generated by Django 3.0.5 on 2020-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_qanda_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='store/category/'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
