# Generated by Django 3.0.5 on 2020-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, upload_to='home/profile_image')),
            ],
        ),
    ]
